/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_DSE_dse1 0x01u        /*!<@brief Drive Strength Enable: High */
#define PCR_IBE_ibe1 0x01u        /*!<@brief Input Buffer Enable: Enables */
#define PORT5_PCR_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT0_22 (number 90), LED_B
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_B_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_B_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_B_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_B_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_B_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_B_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_B_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT0_23 (number 91), LED_G
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_G_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_G_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_G_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_G_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_G_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_G_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_G_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT1_0 (number 92), LED_R
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_R_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_R_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_R_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_R_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_R_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_R_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_R_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT2_3 (number 17), LID_ONOFF_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LID_ONOFF_CTRL_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LID_ONOFF_CTRL_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LID_ONOFF_CTRL_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LID_ONOFF_CTRL_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LID_ONOFF_CTRL_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LID_ONOFF_CTRL_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LID_ONOFF_CTRL_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT2_4 (number 18), SPARE2_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SPARE2_CTRL_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SPARE2_CTRL_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_SPARE2_CTRL_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_SPARE2_CTRL_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPARE2_CTRL_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPARE2_CTRL_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPARE2_CTRL_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT4_7 (number 29), LS_DRIVE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LS_DRIVE_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LS_DRIVE_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LS_DRIVE_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LS_DRIVE_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LS_DRIVE_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LS_DRIVE_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LS_DRIVE_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT5_2 (number 50), LS_SENSE_FLAP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LS_SENSE_FLAP_GPIO GPIO5               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LS_SENSE_FLAP_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LS_SENSE_FLAP_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LS_SENSE_FLAP_PORT PORT5               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LS_SENSE_FLAP_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LS_SENSE_FLAP_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT5_3 (number 51), LS_SENSE_ST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LS_SENSE_ST_GPIO GPIO5               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LS_SENSE_ST_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LS_SENSE_ST_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LS_SENSE_ST_PORT PORT5               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LS_SENSE_ST_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LS_SENSE_ST_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_21 (number 56), LS_SENSE_LIDCLOSE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LS_SENSE_LIDCLOSE_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LS_SENSE_LIDCLOSE_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LS_SENSE_LIDCLOSE_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LS_SENSE_LIDCLOSE_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LS_SENSE_LIDCLOSE_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LS_SENSE_LIDCLOSE_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORT3_20 (number 57), LS_SENSE_LIDOPEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LS_SENSE_LIDOPEN_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LS_SENSE_LIDOPEN_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LS_SENSE_LIDOPEN_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LS_SENSE_LIDOPEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LS_SENSE_LIDOPEN_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LS_SENSE_LIDOPEN_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT3_17 (number 60), RTC_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RTC_INT_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RTC_INT_GPIO_PIN 17U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_RTC_INT_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RTC_INT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RTC_INT_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RTC_INT_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_16 (number 61), HEATER_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HEATER_CTRL_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HEATER_CTRL_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_HEATER_CTRL_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_HEATER_CTRL_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HEATER_CTRL_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HEATER_CTRL_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HEATER_CTRL_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_15 (number 62), SHD_DIR_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SHD_DIR_CTRL_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SHD_DIR_CTRL_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_SHD_DIR_CTRL_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_SHD_DIR_CTRL_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SHD_DIR_CTRL_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SHD_DIR_CTRL_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SHD_DIR_CTRL_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_14 (number 63), SHD_ONOFF_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SHD_ONOFF_CTRL_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SHD_ONOFF_CTRL_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_SHD_ONOFF_CTRL_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_SHD_ONOFF_CTRL_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SHD_ONOFF_CTRL_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SHD_ONOFF_CTRL_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SHD_ONOFF_CTRL_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORT3_13 (number 64), SPARE1_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SPARE1_CTRL_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SPARE1_CTRL_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_SPARE1_CTRL_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_SPARE1_CTRL_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPARE1_CTRL_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPARE1_CTRL_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPARE1_CTRL_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_12 (number 65), LID_REV_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LID_REV_CTRL_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LID_REV_CTRL_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LID_REV_CTRL_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LID_REV_CTRL_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LID_REV_CTRL_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LID_REV_CTRL_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LID_REV_CTRL_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_6 (number 72), I2C_EEPROM_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C_EEPROM_SCK_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_EEPROM_SCK_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_EEPROM_SCK_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT3_1 (number 74), I2C_EEPROM_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C_EEPROM_SDA_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_EEPROM_SDA_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_EEPROM_SDA_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT0_16 (number 84), UART_RXD_HMI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART_RXD_HMI_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART_RXD_HMI_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART_RXD_HMI_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_17 (number 85), UART_TXD_HMI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART_TXD_HMI_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART_TXD_HMI_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART_TXD_HMI_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_18 (number 86), ASB_HMI_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ASB_HMI_INT_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ASB_HMI_INT_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_ASB_HMI_INT_GPIO_PIN 18U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ASB_HMI_INT_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ASB_HMI_INT_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ASB_HMI_INT_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ASB_HMI_INT_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT0_20 (number 88), UART_RXD_DBG
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART_RXD_DBG_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART_RXD_DBG_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART_RXD_DBG_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_21 (number 89), UART_TXD_DBG
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART_TXD_DBG_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART_TXD_DBG_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART_TXD_DBG_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT1_12 (number 5), I2C_SDA_CAMERA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C_SDA_CAMERA_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_SDA_CAMERA_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_SDA_CAMERA_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORT1_13 (number 6), I2C_SCK_CAMERA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C_SCK_CAMERA_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C_SCK_CAMERA_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C_SCK_CAMERA_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORT2_6 (number 20), SLEEP_DRV8912
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SLEEP_DRV8912_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SLEEP_DRV8912_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_SLEEP_DRV8912_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_SLEEP_DRV8912_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SLEEP_DRV8912_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SLEEP_DRV8912_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SLEEP_DRV8912_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT2_7 (number 21), FAULT_DRV8912
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_FAULT_DRV8912_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_FAULT_DRV8912_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_FAULT_DRV8912_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_FAULT_DRV8912_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_FAULT_DRV8912_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_FAULT_DRV8912_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT4_0 (number 22), SPI_SDO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_SDO_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_SDO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_SDO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT4_1 (number 23), SPI_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_SCK_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_SCK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_SCK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT4_2 (number 24), SPI_SDI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI_SDI_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI_SDI_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI_SDI_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT4_3 (number 25), PCS_TDC1000_1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PCS_TDC1000_1_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PCS_TDC1000_1_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PCS_TDC1000_1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT4_4 (number 26), PCS_TDC1000_2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PCS_TDC1000_2_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PCS_TDC1000_2_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PCS_TDC1000_2_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT4_5 (number 27), PCS_DRV89XX_2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PCS_DRV89XX_2_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PCS_DRV89XX_2_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PCS_DRV89XX_2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT4_6 (number 28), PCS_DRV89XX_1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PCS_DRV89XX_1_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PCS_DRV89XX_1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PCS_DRV89XX_1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT4_13 (number 36), TC78H660_MODE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TC78H660_MODE_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_TC78H660_MODE_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_TC78H660_MODE_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_TC78H660_MODE_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TC78H660_MODE_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TC78H660_MODE_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TC78H660_MODE_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT4_15 (number 37), TC78H660_STBY
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TC78H660_STBY_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_TC78H660_STBY_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_TC78H660_STBY_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_TC78H660_STBY_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TC78H660_STBY_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TC78H660_STBY_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TC78H660_STBY_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT4_16 (number 38), MOTOR1_ONOFF_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOTOR1_ONOFF_CTRL_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOTOR1_ONOFF_CTRL_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_MOTOR1_ONOFF_CTRL_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_MOTOR1_ONOFF_CTRL_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR1_ONOFF_CTRL_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR1_ONOFF_CTRL_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR1_ONOFF_CTRL_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORT5_0 (number 48), MOTOR2_ONOFF_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOTOR2_ONOFF_CTRL_GPIO GPIO5               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOTOR2_ONOFF_CTRL_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_MOTOR2_ONOFF_CTRL_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_MOTOR2_ONOFF_CTRL_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR2_ONOFF_CTRL_PORT PORT5               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR2_ONOFF_CTRL_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR2_ONOFF_CTRL_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT5_1 (number 49), MOTOR2_DIR_CTRL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOTOR2_DIR_CTRL_GPIO GPIO5               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOTOR2_DIR_CTRL_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_MOTOR2_DIR_CTRL_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_MOTOR2_DIR_CTRL_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR2_DIR_CTRL_PORT PORT5               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR2_DIR_CTRL_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR2_DIR_CTRL_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
