/*
 * GPIOSignals.h
 *
 *  Created on: 11-Jul-2025
 *      Author: Jawahar Arumugam
 */

#ifndef GPIOSIGNALS_H_
#define GPIOSIGNALS_H_

#include "pin_mux.h"
#include "fsl_gpio.h"

/********************Constants for Pin Control */

#define GPIO_PIN_ZERO	0
#define GPIO_PIN_ONE	1

#define GPIO_PIN_LOW	0
#define GPIO_PIN_HIGH	1


/********************MACRO to control GPIO Pins*********/

//LOW on the GPIO pin light the LED
#define GREEN_LED_ON()				GPIO_PinWrite(BOARD_INITPINS_LED_G_GPIO, BOARD_INITPINS_LED_G_PIN, GPIO_PIN_LOW);
#define GREEN_LED_OFF()				GPIO_PinWrite(BOARD_INITPINS_LED_G_GPIO, BOARD_INITPINS_LED_G_PIN, GPIO_PIN_HIGH);
#define GREEN_LED_TOGGLE()   		GPIO_PortToggle(BOARD_INITPINS_LED_G_GPIO, BOARD_INITPINS_LED_G_PIN_MASK);

#define BLUE_LED_ON()				GPIO_PinWrite(BOARD_INITPINS_LED_B_GPIO, BOARD_INITPINS_LED_B_PIN, GPIO_PIN_LOW);
#define BLUE_LED_OFF()				GPIO_PinWrite(BOARD_INITPINS_LED_B_GPIO, BOARD_INITPINS_LED_B_PIN, GPIO_PIN_HIGH);
#define BLUE_LED_TOGGLE()   		GPIO_PortToggle(BOARD_INITPINS_LED_B_GPIO, BOARD_INITPINS_LED_B_PIN_MASK);

#define RED_LED_ON()				GPIO_PinWrite(BOARD_INITPINS_LED_R_GPIO, BOARD_INITPINS_LED_R_PIN, GPIO_PIN_LOW);
#define RED_LED_OFF()				GPIO_PinWrite(BOARD_INITPINS_LED_R_GPIO, BOARD_INITPINS_LED_R_PIN, GPIO_PIN_HIGH);
#define RED_LED_TOGGLE()   			GPIO_PortToggle(BOARD_INITPINS_LED_R_GPIO, BOARD_INITPINS_LED_R_PIN_MASK);


//Limit switch Drive signal
//Drive the pin LOW to make the LS_DRIVE output HIGH (RS232C output ~+Ve)
//Drive the pin HIGH to make the LS_DRIVE output LOW (RS232C output ~-Ve)
#define LS_DRIVE_HIGH()		GPIO_PinWrite(BOARD_INITPINS_LS_DRIVE_GPIO, BOARD_INITPINS_LS_DRIVE_PIN, GPIO_PIN_LOW);
#define LS_DRIVE_LOW()		GPIO_PinWrite(BOARD_INITPINS_LS_DRIVE_GPIO, BOARD_INITPINS_LS_DRIVE_PIN, GPIO_PIN_HIGH);

//LID_OPEN and LID_CLOSE LS got interchanged in HW. Corrected in FW
#define READ_LS_SENSE_LIDOPEN()		GPIO_PinRead(BOARD_INITPINS_LS_SENSE_LIDCLOSE_GPIO, BOARD_INITPINS_LS_SENSE_LIDCLOSE_PIN)
#define READ_LS_SENSE_LIDCLOSE()	GPIO_PinRead(BOARD_INITPINS_LS_SENSE_LIDOPEN_GPIO, BOARD_INITPINS_LS_SENSE_LIDOPEN_PIN)
#define READ_LS_SENSE_FLAP()		GPIO_PinRead(BOARD_INITPINS_LS_SENSE_FLAP_GPIO, BOARD_INITPINS_LS_SENSE_FLAP_PIN)
#define READ_LS_SENSE_ST()			GPIO_PinRead(BOARD_INITPINS_LS_SENSE_ST_GPIO, BOARD_INITPINS_LS_SENSE_ST_PIN)

//Heater Control
#define HEATER_OFF()		GPIO_PinWrite(BOARD_INITPINS_HEATER_CTRL_GPIO, BOARD_INITPINS_HEATER_CTRL_PIN, GPIO_PIN_LOW);
#define HEATER_ON()			GPIO_PinWrite(BOARD_INITPINS_HEATER_CTRL_GPIO, BOARD_INITPINS_HEATER_CTRL_PIN, GPIO_PIN_HIGH);

//Shredder Motor Control
#define SHD_STOP()			GPIO_PinWrite(BOARD_INITPINS_SHD_ONOFF_CTRL_GPIO, BOARD_INITPINS_SHD_ONOFF_CTRL_PIN, GPIO_PIN_LOW);
#define SHD_START()			GPIO_PinWrite(BOARD_INITPINS_SHD_ONOFF_CTRL_GPIO, BOARD_INITPINS_SHD_ONOFF_CTRL_PIN, GPIO_PIN_HIGH);

#define SHD_DIR_CW()		GPIO_PinWrite(BOARD_INITPINS_SHD_DIR_CTRL_GPIO, BOARD_INITPINS_SHD_DIR_CTRL_PIN, GPIO_PIN_LOW);
#define SHD_DIR_CCW()		GPIO_PinWrite(BOARD_INITPINS_SHD_DIR_CTRL_GPIO, BOARD_INITPINS_SHD_DIR_CTRL_PIN, GPIO_PIN_HIGH);

//LID_REV_CTRL and LID_ONOFF_CTRL signals were interchanged in the schematic and that is taken care here
//Lid Power Control
#define LID_POWER_OFF()			GPIO_PinWrite(BOARD_INITPINS_LID_REV_CTRL_GPIO, BOARD_INITPINS_LID_REV_CTRL_PIN, GPIO_PIN_LOW);
#define LID_POWER_ON()			GPIO_PinWrite(BOARD_INITPINS_LID_REV_CTRL_GPIO, BOARD_INITPINS_LID_REV_CTRL_PIN, GPIO_PIN_HIGH);

//Lid Reverse Control Relay
#define LID_MOTOR_DIR_CLOSE()	GPIO_PinWrite(BOARD_INITPINS_LID_ONOFF_CTRL_GPIO, BOARD_INITPINS_LID_ONOFF_CTRL_GPIO_PIN, GPIO_PIN_LOW);
#define LID_MOTOR_DIR_OPEN()	GPIO_PinWrite(BOARD_INITPINS_LID_ONOFF_CTRL_GPIO, BOARD_INITPINS_LID_ONOFF_CTRL_GPIO_PIN, GPIO_PIN_HIGH);


//Spare Relay Control
#define SPARE1_RELAY_OFF()	GPIO_PinWrite(BOARD_INITPINS_SPARE1_CTRL_GPIO, BOARD_INITPINS_SPARE1_CTRL_PIN, GPIO_PIN_LOW);
#define SPARE1_RELAY_ON()	GPIO_PinWrite(BOARD_INITPINS_SPARE1_CTRL_GPIO, BOARD_INITPINS_SPARE1_CTRL_PIN, GPIO_PIN_HIGH);
//Spare Relay Control
#define SPARE2_RELAY_OFF()	GPIO_PinWrite(BOARD_INITPINS_SPARE2_CTRL_GPIO, BOARD_INITPINS_SPARE2_CTRL_PIN, GPIO_PIN_LOW);
#define SPARE2_RELAY_ON()	GPIO_PinWrite(BOARD_INITPINS_SPARE2_CTRL_GPIO, BOARD_INITPINS_SPARE2_CTRL_PIN, GPIO_PIN_HIGH);

//ASB_HMI_INT Control: Falling Edge interrupt
#define HMI_INT_ACTIVE()	GPIO_PinWrite(BOARD_INITPINS_ASB_HMI_INT_GPIO, BOARD_INITPINS_ASB_HMI_INT_PIN, GPIO_PIN_LOW);
#define HMI_INT_INACTIVE()	GPIO_PinWrite(BOARD_INITPINS_ASB_HMI_INT_GPIO, BOARD_INITPINS_ASB_HMI_INT_PIN, GPIO_PIN_HIGH);



#endif /* GPIOSIGNALS_H_ */
